### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by halbodb** [TheoIsDumb/CopyOptimize#1]
Hi there,

Sometimes when I copy an object path/s I get the following error:

Traceback (most recent call last):
  File "C:\Users\hdbAdmin\AppData\Roaming\inkscape\extensions\org.theoisdumb.CopyOptimize\CopyOptimize-master\main.py", line 35, in <module>
    CopyOptimize().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 250, in run
    self.save_raw(self.effect())
  File "C:\Users\hdbAdmin\AppData\Roaming\inkscape\extensions\org.theoisdumb.CopyOptimize\CopyOptimize-master\main.py", line 32, in effect
    inkex.utils.debug(scourString(svg_string, options))
  File "C:\Program Files\Inkscape\lib\python3.10\site-packages\scour\scour.py", line 3681, in scourString
    doc = xml.dom.minidom.parseString(in_string)
  File "C:\Program Files\Inkscape\lib\python3.10\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "C:\Program Files\Inkscape\lib\python3.10\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Program Files\Inkscape\lib\python3.10\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: unbound prefix: line 31, column 4

This is my  Inkscape version:
Inkscape 1.3 (0e150ed6c4, 2023-07-21)

    GLib version:     2.76.4
    GTK version:      3.24.38
    glibmm version:   2.66.6
    gtkmm version:    3.24.7
    libxml2 version:  2.11.4
    libxslt version:  1.1.38
    Cairo version:    1.17.7
    Pango version:    1.50.14
    HarfBuzz version: 8.0.1
    OS version:       Windows 11 22H2

I will really appreciate it if you can help me sort out this issue.

**Comment by theophinetheodore** [comment]
Sorry for the late reply, sir. Didn't open GitHub for a few days - was travelling and all. I'll look into it tomorrow.

BTW does this occur everytime you copy something, or just with a single item/collection of items?

Thanks for the heads-up. Really appreciate it.

**Comment by halbodb** [comment]
Hello,

I wanted to thank you for your response and your dedication to your Inkscape extension.
I understand that you have been away due to travel, and I appreciate your prompt attention upon your return.
Regarding the error I reported, This error occurs sometimes when I attempt to copy an SVG path from an external Inkscape document and paste it into my current workspace.
Your interest in the specific circumstances is greatly appreciated.
Your dedication doesn't go unnoticed, and I'm confident that the solution will benefit the Inkscape community.
Looking forward to your insights and updates.

Here is more of the error message:
NOTE: The error messages will be the same except for the last line where the column number will be different..

Traceback (most recent call last):
  File "C:\Users\hdbAdmin\AppData\Roaming\inkscape\extensions\org.theoisdumb.CopyOptimize\CopyOptimize-master\main.py", line 35, in <module>
    CopyOptimize().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 250, in run
    self.save_raw(self.effect())
  File "C:\Users\hdbAdmin\AppData\Roaming\inkscape\extensions\org.theoisdumb.CopyOptimize\CopyOptimize-master\main.py", line 32, in effect
    inkex.utils.debug(scourString(svg_string, options))
  File "C:\Program Files\Inkscape\lib\python3.10\site-packages\scour\scour.py", line 3681, in scourString
    doc = xml.dom.minidom.parseString(in_string)
  File "C:\Program Files\Inkscape\lib\python3.10\xml\dom\minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "C:\Program Files\Inkscape\lib\python3.10\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Program Files\Inkscape\lib\python3.10\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: unbound prefix: line 38, column 4

...
xml.parsers.expat.ExpatError: unbound prefix: line 1, column 4072

**Comment by theophinetheodore** [comment]
Sorry again. BTW, I think this has something to do with Scour. Or maybe Windows issues, I guess. (I haven't tested it on Windows or macOS.)

BTW, you still didn't answer my question, sir. Does this happen everytime you select an element or foes this occur only with a particular element/group of elements?

**Comment by halbodb** [comment]
Thanks for coming back to me. I will double-check and report back to you in a few days.

**Comment by theophinetheodore** [comment]
hey @halbodb any updates? been waiting for your reply all these days. maybe you got busy with life and stuff?

**Comment by halbodb** [comment]
I hope this message finds you well.
Currently, I am swamped with other commitments that demand my immediate attention.
However, please rest assured that I have not forgotten about the issue, and I will dedicate the time it deserves very soon.
Thank you for your understanding.

**Comment by theophinetheodore** [comment]
No worries @halbodb!
I'll keep this open btw.

**Comment by halbodb** [comment]
Hi,

After a long delay, I can finally provide some feedback regarding the issue I encountered:

When I apply **Linear and/or Radial Gradients** to an SVG path, I notice that the error occurs when attempting to copy and paste with the app. However, when I revert the path to its original plain form, the error disappears, and I can use the app without any problems again...
Interestingly, I observed that this error does not manifest when I use the **Mesh Gradient** method.

If you manage to pinpoint and rectify this error, you'll undoubtedly be my hero!
I'm looking forward to future updates and enhancements for this app. It has become an essential part of my Inkscape toolkit, and I'm excited to see how it evolves.

Your work is greatly appreciated.

Best regards
